.TH frzscr 1 "June 2025" "1.0.0" "User Commands"
.SH NAME
frzscr \- freeze screen

.SH SYNOPSIS
.B frzscr
[\fB\-Cvh\fR]
[\fB\-o\fR \fIOUTPUT\fR]
[\fB\-t\fR \fITIMEOUT\fR]
[\fB\-s\fR \fISIGNUM\fR]
[\fB\-c\fR \fICMD\fR [\fIARG\fR]...]

.SH DESCRIPTION
.B frzscr
creates an illusion of frozen screen by capturing your screen's contents and displaying it as an overlay. This is particularly useful for taking screenshots.

.SH OPTIONS
.TP
\fB\-o\fR \fIOUTPUT\fR
Only freeze the specified \fIOUTPUT\fR (e.g. eDP-1).
.TP
\fB\-t\fR \fITIMEOUT\fR
Exit after TIMEOUT seconds. If \fB-c\fR options is used, \fBfrzscr\fR will also kill the child process by sending SIGTERM (or \fISIGNUM\fR if \fB-s\fR is used) to its process group.
.TP
\fB\-s\fR \fISIGNUM\fR
Send signal number \fISIGNUM\fR to child process group instead of SIGTERM.
.TP
\fB\-c\fR \fICMD\fR [\fIARG\fR]...
Fork the specified command and wait for it to exit. This terminates option list, and all arguments after \fB\-c\fR are treated as \fICMD\fR's argv (see \fBexecvp\fR(3)). The command is run in a new process group (see \fBsetpgid\fR(2)).
.TP
\fB\-C\fR
Include cursor in the overlay.
.TP
\fB\-v\fR
Enable debug output.
.TP
\fB\-h\fR
Print help message and exit.

.SH EXAMPLES
Freeze screen for 5 seconds and exit.
.PP
.RS
.nf
frzscr \-t 5
.fi
.RE
.PP
Example for taking screenshots. Note the double \fB-c\fR flag, which is not a typo. The first flag is interpreted by \fBfrzscr\fR itself, and the second is passed to \fBsh\fR(1).
.PP
.RS
.nf
frzscr \-c sh \-c 'grim \-g "$(slurp)" \- | wl\-copy \-t "image/png"'
.fi
.RE

.SH NOTES
Launching \fBfrzscr\fR without arguments will freeze your screen until the process is killed and you might softlock yourself. Use either \fB\-t\fR or \fB\-c\fR options.

The wayland spec states: "Multiple surfaces can share a single layer, and ordering within a single layer is undefined." \fBfrzscr\fR assumes that newer surfaces are put on top of the older ones, and creates its own surfaces before forking the command specified with \fB-c\fR option, which allows programs like \fBslurp\fR(1) to work with \fBfrzscr\fR. This is compositor-dependant, but is known to work on hyprland, niri and sway.

.SH BUGS
Please report bugs to https://github.com/heather7283/frzscr/issues.
.PD 0
.IP \(bu 4
Provide output of \fBfrzscr\fR with \fB-v\fR option and WAYLAND_DEBUG=1 envvar set.
.IP \(bu 4
Provide backtrace with symbols if you experience a crash.
.IP \(bu 4
Describe steps necessary to reproduce the issue.
.PD

.SH SEE ALSO
Another project that does similar things: https://github.com/Jappie3/wayfreeze
.PP
.BR grim (1),
.BR slurp (1),
.BR hyprpicker (1)
